[package]
name = "sss"
version = "0.0.1"
edition = "2021"
description = "A Shamir Secret Sharing"
license = "MIT"
repository = "https://github.com/diogogomesaraujo/sss"
categories = ["cryptography"]
keywords = ["sss", "keys"]
readme = "README.md"

[dependencies]
rand = "0.9.0"
rug = "1.27.0"
