[package]
name = "thresh-sig"
version = "0.0.3"
edition = "2021"
description = "A threshold signature library."
license = "MIT"
repository = "https://github.com/diogogomesaraujo/thresh"
categories = ["cryptography"]
keywords = ["sss", "threshold", "schnorr"]
readme = "README.md"

[dependencies]
rand = "0.9.0"
rug = "1.27.0"
sha256 = "1.6.0"
